services:
  ner-service:
    build:
      context: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: >
      uv run python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn web:app --host
      0.0.0.0 --port 80 --proxy-headers --timeout-keep-alive 300 --workers 1
      --reload --reload-dir /app
    ports:
      - "8086:80"
      - "5678:5678"
    networks:
      - app-decide_default
    environment:
      SEGMENTATION__LLM__API_KEY: "SECRET" # API key for the segmentation LLM provider (OpenAI, Mistral...)
      TRANSLATION__ETRANSLATION__BEARER_TOKEN: "SECRET" # When translation provider is etranslation, this bearer token will be used for authentication
      TRANSLATION__ETRANSLATION__PASSWORD: "SECRET" # When translation provider is etranslation and bearer token is not set or empty, this password (in combination with the username) will be used for authentication
      MODE: "development"
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      CONFIG_PATH: /config/config.json
      COMPOSE_FILE: /tmp/docker-compose.yaml
      COMPOSE_SERVICE: ner-service
    restart: no
    volumes:
      - ./:/app
      - ./config.json:/config/config.json:ro
      - ./docker-compose.yaml:/tmp/docker-compose.yaml

networks:
  app-decide_default:
    external: true
